name: CI
on: push
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
          sudo gem install bundler
      - name: Prepare
        run: |
          bundle install
          npm ci
          docker pull lambci/lambda:build-ruby2.7
      - name: Test
        run: bundle exec rspec
      - name: Bundle with Native Extensions
        run: |
          docker run --rm -v $PWD:/var/task lambci/lambda:build-ruby2.7 bash <<EOF
            docker run
            mkdir /tmp/bin
            yum install -y cmake3 openssl-devel libicu-devel
            ln -s /tmp/bin/cmake /usr/bin/cmake3
            env PATH=/tmp/bin:$PATH bundle install --without test --path=vendor/bundle
          EOF
      - name: Package
        run: |
          npm run pack
#      - name: Deploy
#        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
#        run: npm run deploy
#        env:
#          AWS_DEFAULT_REGION: us-east-1
#          AWS_REGION: us-east-1
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
